module mvwrap
use precision_model
use mvstat
IMPLICIT NONE

contains
SUBROUTINE MVNDIST(N, COVRNC, NU, M, LOWER, CONSTR, UPPER, INFIN, DELTA, &
        MAXPTS, ABSEPS, RELEPS, ERROR, VALUE, NEVALS, INFORM)
      INTEGER,                         INTENT(IN)  :: N, NU, M, MAXPTS
      REAL(KIND=STND), DIMENSION(M),   INTENT(IN)  :: LOWER, UPPER, DELTA
      REAL(KIND=STND), DIMENSION(N,N), INTENT(IN)  :: COVRNC
      REAL(KIND=STND), DIMENSION(M,N), INTENT(IN)  :: CONSTR
      INTEGER,    DIMENSION(M),        INTENT(IN)  :: INFIN
      REAL(KIND=STND),                 INTENT(IN)  :: RELEPS, ABSEPS
      INTEGER,                         INTENT(OUT) :: INFORM, NEVALS
      REAL(KIND=STND),                 INTENT(OUT) :: ERROR, VALUE

      CALL MVDIST(N, COVRNC, NU, M, LOWER, CONSTR, UPPER, INFIN, DELTA, MAXPTS, ABSEPS, RELEPS, ERROR, VALUE, NEVALS, INFORM)
END SUBROUTINE MVNDIST
end module mvwrap
